version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "stack"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "app"
    volumes:
     - mysql_db:/var/lib/mysql
     - ./mysql/logs:/var/log/mysql
     - ./mysql/conf.d:/etc/mysql/conf.d
volumes:
  mysql_db:
    driver: "local"
